### ISSUE TITLE
Telegram client initialization...

### ISSUE THREAD

**Issue by hardwin1014** [IvanGlinkin/CCTV#20]
[ * ] Telegram client initialization...Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
![image](https://github.com/IvanGlinkin/CCTV/assets/81634902/0610868e-81a2-4e01-a1f3-78b6ded57c0e)

**Comment by hardwin1014** [comment]
> 启动 start.py 应用程序后，我得到以下信息：
> 
> `[ * ] Telegram client initialization...Please enter your phone (or bot token):`
> 
> 我应该在这里输入什么？

visit https://my.telegram.org/auth web-site
input your phone number
input the confirmation/login code
follow "API development tools" link
register the application
get App's api_id, api_hash, title and name

**Comment by hardwin1014** [comment]
> 我和我的同事刚刚测试过 - 一切正常。我可能猜你输入了错误的数据或者你的互联网提供商阻止了电报

OK thanks

**Comment by IvanGlinkin** [comment]
> I get the following once I started the start.py application:
> 
> `[ * ] Telegram client initialization...Please enter your phone (or bot token):`
> 
> What should I input here?

Thanks @hardwin1014 for help.
That is exactly what you have to do. After launching the app you need to put that data into terminal to get a session and start working.

**Comment by fklement** [comment]
> > I get the following once I started the start.py application:
> > `[ * ] Telegram client initialization...Please enter your phone (or bot token):`
> > What should I input here?
> 
> Thanks @hardwin1014 for help. That is exactly what you have to do. After launching the app you need to put that data into terminal to get a session and start working.

Of course I did this, because I followed the Readme.
But unfortunately this message still pops up.

**Comment by silversegarra** [comment]
Hello, I understand that TG Phone: is Target, phone number?

**Comment by hardwin1014** [comment]
> > > 启动 start.py 应用程序后，我得到以下信息：
> > > `[ * ] Telegram client initialization...Please enter your phone (or bot token):`
> > > 我应该在此处输入什么？
> > 
> > 
> > 谢谢@hardwin1014求助。这正是你必须做的。启动应用程序后，您需要将该数据放入终端以获取会话并开始工作。
> 
> 我当然这样做了，因为我遵循了自述文件。 但不幸的是，这条消息仍然弹出。

Go to that website and register, get the api_id and api_hash in the project, and then run

**Comment by NordicBeer** [comment]
> > > После запуска приложения start.py я получаю следующее: 
> > > `[ * ] Telegram client initialization...Please enter your phone (or bot token):`
> > > Что мне следует сюда ввести?
> > 
> > 
> > Спасибо @hardwin1014для помощи.  Это именно то, что вам нужно сделать.  После запуска приложения вам необходимо поместить эти данные в терминал, чтобы получить сеанс и начать работу.
> 
> Конечно, я сделал это, потому что следовал Readme. Но, к сожалению, это сообщение все еще появляется.

In the readme and in my config.yaml, "api_id: 00000000" was not surrounded by single quotes.  Make api_id: '00000000'.
It works for me now.

**Comment by Linncharm** [comment]
i have those problems too,have you already fix it ?

**Comment by hardwin1014** [comment]
> 我也遇到了这些问题。您解决了吗？

并没有，目前问题就是api链接问题，我开了VPN也不行

**Comment by Linncharm** [comment]
> > 我也遇到了这些问题。您解决了吗？
> 
> 并没有，目前问题就是api链接问题，我开了VPN也不行

我目前在windows运行的，猜测最大的可能是cmd没有使用系统使用的vpn代理，怎么设置都不行，ping不通外网

**Comment by hardwin1014** [comment]
> > > 我也遇到了问题。您解决了吗？
> > 
> > 
> > 没有，目前问题就是api链接问题，我开了VPN也不行
> 
> 我目前在windows运行的，猜测最大的可能是cmd没有使用系统使用的vpn代理，怎么设置都不行，ping不通外网



> > > 我也遇到了问题。您解决了吗？
> > 
> > 
> > 没有，目前问题就是api链接问题，我开了VPN也不行
> 
> 我目前在windows运行的，猜测最大的可能是cmd没有使用系统使用的vpn代理，怎么设置都不行，ping不通外网

我开了vpn也没搞通
