### ISSUE TITLE
.html are not created, how to fix it?

### ISSUE THREAD

**Issue by Ha1fCheese** [IvanGlinkin/CCTV#24]
![image](https://github.com/IvanGlinkin/CCTV/assets/72697591/7e611f20-ddca-4282-893b-b25aabfccbda)
_.html are not created, how to fix it?_

**Comment by makspo1nt** [comment]
just wait for the full completion of the execution

**Comment by IvanGlinkin** [comment]
> just wait for the full completion of the execution

thanks for the reply.
Yeah, just wait till the app finishes the work. the html will be generated and open automatically
