### ISSUE TITLE
Impossible to get a combined file

### ISSUE THREAD

**Issue by Axrxaxra** [IvanGlinkin/CCTV#26]
In the end, after successful json and html, he writes that the combined file has been successfully created, but he does not throw me anywhere, as shown in the video, and no link and no files are given anywhere.

**Comment by Axrxaxra** [comment]
![Screenshot_20240509_014806_Termux](https://github.com/IvanGlinkin/CCTV/assets/169313390/3a872b0e-4e24-4f94-89d8-cc96535699a3)

**Comment by paracosm17** [comment]
Check the `reports-html` folder. `_combined_data.html` should be there

**Comment by Axrxaxra** [comment]
Interesting, I don't have this folder anywhere. I also checked it using PC

**Comment by paracosm17** [comment]
You don't need to create folders manually.
Try to write `ls` in the root folder of the project (CCTV). You will see the `reports-html` folder. Next, write `cd reports-html`, you will move to this folder. Write `ls` again. You will see all the generated html files. You can also write `pwd` to see the full path to this folder on the device

**Comment by Axrxaxra** [comment]
![Screenshot_20240509_142651_Termux](https://github.com/IvanGlinkin/CCTV/assets/169313390/d455d986-622b-49f4-bdf5-c8198fda4d73)

Oh, thanks, it works. But how can I get to the browser page from here, like it was shown in video?

**Comment by paracosm17** [comment]
You just need to open the file `_combined_data.html `. 
If you are doing this with android, try opening file explorer and following the path that you saw after the `pwd` command. Find this file and just open it, it should open in the browser. You can also send this file to your telegram and open it on your computer

**Comment by Axrxaxra** [comment]
![Screenshot_20240509_155227_Files](https://github.com/IvanGlinkin/CCTV/assets/169313390/e40377df-28be-4099-b6fb-10b5f7df7b4e)
Ok, but there is no "com.termux" folder..

**Comment by Axrxaxra** [comment]
![Screenshot_20240509_173541_Chrome](https://github.com/IvanGlinkin/CCTV/assets/169313390/1eff1400-c650-401a-bc59-5bbdcb7a02ba)
After opening "_combined_data.html" I got this from Chrome

**Comment by paracosm17** [comment]
The stylesheets and scripts have not loaded. You should try to just do it all from your computer, not from your phone.

**Comment by Axrxaxra** [comment]
shiit, i don't even know, how to use terminal or termux on windows properly......
