### ISSUE TITLE
The password is not entered when it comes to the stage of entering the telegram password

### ISSUE THREAD

**Issue by GODUKX** [IvanGlinkin/CCTV#28]
Here I enter the phone number, the code, and when I need to enter the password, it does not want to be found, does not respond to the keyboard at all, how to decide?

**Comment by protector131090** [comment]
> Here I enter the phone number, the code, and when I need to enter the password, it does not want to be found, does not respond to the keyboard at all, how to decide?

same here

**Comment by paracosm17** [comment]
The password is entered, you just don't see it. When it comes to entering a password, just enter the password and press enter. It's okay that you don't see how it's written.

**Comment by GODUKX** [comment]
> The password is entered, you just don't see it. When it comes to entering a password, just enter the password and press enter. It's okay that you don't see how it's written.

I tried it this way, it didn't work. He writes that the password is incorrect. Although I entered it correctly

**Comment by paracosm17** [comment]
Well, it's weird, everything should work, it worked for me with a 2FA password.
These tips may seem trivial, but still, try to run the program again and enter the password. Make sure that the correct layout is enabled, the CapsLock key is not pressed, and that you are entering the correct password for sure.

**Comment by GODUKX** [comment]
> Well, it's weird, everything should work, it worked for me with a 2FA password. These tips may seem trivial, but still, try to run the program again and enter the password. Make sure that the correct layout is enabled, the CapsLock key is not pressed, and that you are entering the correct password for sure.

I entered it again, it worked. So that's it, thanks
