### ISSUE TITLE
Скорость и другие параметры

### ISSUE THREAD

**Issue by sai84** [IvanGlinkin/CCTV#35]
Иван, подскажите пожалуйста значение параметра скорость. Что он определяет ? Это фильтр и отбираются только те пользователи, которые двигаются меньше / больше этой скорости? Как это определяется? Между двумя замерами объект должен перемещаться с такой скоростью или между всеми 25? Можно подробнее пожалуйста по этому параметру, а также по двум другим:
- задержка в секундах - я так понимаю, это для снижения вероятности блокировки аккаунта?
- радиус (диаметр) в метрах - как работает данный параметр? Все, что выходит за данный радиус/диаметр (? какой вариант), не попадает в выборку? 

Спасибо за инструмент!

**Comment by IvanGlinkin** [comment]
Приветствую. Спасибо за положительный отзыв.
Параметр скорость - с какой скоростью Вы двигаетесь между точками перед получением данных. Скажем так, если вы двигаетесь со скоростью 90 км/ч, то время между запросами - 30 секунд. Если поставите скорость выше - то время между запросами будет меньше и наоборот.
Для чего сделано - все верно, для обхода блокировок телеграммом.
Радиус - да, какую площадь хотите покрыть - полкилометра, километр, 2... чем больше радиус - тем больше запросов нужно делать. для 1200 метров - 25 запросов, для 2400 метров - 49 запросов, и т.д.

Еща раз спасибо за положительный отзыв :)
