### ISSUE TITLE
How is the format of the general_settings.py file?

### ISSUE THREAD

**Issue by Bigyls** [IvanGlinkin/CCTV#4]
All is in the title

**Comment by Bigyls** [comment]
Thanks to the reply, In fact, I'm looking for the file `general_settings.py` but it's there https://github.com/IvanGlinkin/CCTV/blob/main/backend/general_settings.py. Maybe you can link it in the README for other people ?

**Comment by IvanGlinkin** [comment]
> Thanks to the reply, In fact, I'm looking for the file `general_settings.py` but it's there https://github.com/IvanGlinkin/CCTV/blob/main/backend/general_settings.py. Maybe you can link it in the README for other people ?

oooh, understood. sure, valid point. will do
